name: Instacams
favicon: null
layout_spectrum: 1
typography_spectrum: 0.61925
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4078b9'
    - '#ffffff'
    - '#6c99d2'
    - '#9db8d7'
    - '#d2ddea'
  brandStrength: 0.33300523832440376
  lightness: 0.8550943997688591
  saturation: 0.10271583823487163
  rhythmicContrast: 0.0017788929399102926
purpose: []
