name: Instacams
favicon: null
layout_spectrum: 0.8765471996739507
typography_spectrum: 0.2946520915720612
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.33300523832440376
  lightness: 0.8550943997688591
  saturation: 0.10271583823487163
  rhythmicContrast: 0.0017788929399102926
purpose: []
